---
title: Instalando e executando DrugCLIP no Escola de Sagres
author: "Fernando Náufel"
date: now
date-format: "DD/MM/YYYY HH:mm"
lang: pt
engine: knitr
execute: 
  echo: true
  eval: false
  warning: true
  error: true
  include: true

# bibliography: bibliography.bib

# Português:
# csl: universidade-do-porto-faculdade-de-engenharia-chicago-pt-crono.csl

format:
  html:
    toc: true  
    toc-depth: 3
    number-sections: true
    number-depth: 3
    theme: 
      - journal
      - _custom.scss
#    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: ^(?:http:|https:)\/\/fnaufel\.github\.io
    df-print: paged
    code-link: true
    code-copy: true
    code-tools: true
    self-contained: true
---

# Sobre este documento

???


# Objetivos

???


# Instalar

## Permitir a instalação de pacotes como não-administrador

Segundo o [Guia de Uso do Spack](https://docs.google.com/document/d/1UX1CC6DMGsyAO0vzSoc_Up2SIDlh_Jzxw_w7fEEyx-A):

1. Devemos criar pastas para cache e armazenamento dos arquivos:

   ```{bash}
   mkdir ~/spack
   mkdir ~/spack/source_cache
   ```

1. Devemos editar o arquivo de configuração `~/.spack/config.yaml` para conter as linhas (substituir `USUÁRIO` pelo nome de usuário):

   ```{bash}
   config:
     install_tree: /home/USUÁRIO/spack
     build_jobs: 4
     source_cache: /home/USUÁRIO/.spack/source_cache
   ```


## Instalar dependências

O [README](https://github.com/fnaufel/DrugCLIP/blob/main/README.md) do repositório do DrugCLIP diz que as dependências são as mesmas do Uni-mol.

O [repositório do Uni-mol](https://github.com/deepmodeling/Uni-Mol/tree/main/unimol) lista como dependências:

- [Uni-Core](https://github.com/dptech-corp/Uni-Core) (*framework* distribuído para Pytorch),
- Rdkit versão 2022.9.5.

Aparentemente, o DrugCLIP traz sua própria cópia do Uni-mol. Não é necessário instalar o Uni-Mol separadamente.


### Verificar CUDA

Precisamos saber a versão do CUDA para a instalação correta do Pytorch.  

Vamos descobrir isto em um nó de GPU:

```{bash}
srun --partition=gpu --gres=gpu:1 --time=00:05:00 --pty bash
```

Isto nos leva a um *shell* em um nó de GPU. Ali, digitamos

```{bash}
nvcc --version
```

A saída é

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:19:38_PST_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0
```

No mesmo nó, rodamos, para mais detalhes

```{bash}
nvidia-smi
```

A saída é

```
Mon Mar 23 15:16:38 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A2                      On  |   00000000:41:00.0 Off |                    0 |
|  0%   34C    P8              8W /   60W |       0MiB /  15356MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

### Instalar o Pytorch

Segundo `spack`, a versão preferida do Pytorch é a 2.5.1:

```{bash}
spack info py-torch
```

Trecho da saída:

```
(...)
Preferred version:  
    2.5.1     [git] https://github.com/pytorch/pytorch.git at commit a8d6afb511a69687bbb2b7e88a3cf67917e1697e
(...)
```

O `spack` vai compilar o fonte do Pytorch. Mas, para isto, precisamos instalar uma versão mais nova do `gcc`:

```{bash}
spack install gcc@13.3.0
```

Depois, precisamos carregar o pacote que acabamos de instalar:

```{bash}
spack load gcc@13.3.0
```

Para confirmar a versão:

```{bash}
gcc --version
```

Precisamos agora registrar esta versão do `gcc` com o Spack:

```{bash}
spack compiler find
```

Vamos carregar, também, uma versão do Python:

```{bash}
spack load python@3.11
```

Para confirmar a versão:

```{bash}
python --version
```

Para instalar o Pytorch com suporte a CUDA, precisamos especificar algumas informações sobre a GPU. Usando a saída do comando `nvidia-smi`, verificamos que a versão do CUDA é 12.4. Pesquisando o modelo da GPU, descobrimos que o valor correto de `cuda_arch` é 86:

```{bash}
spack install py-torch +cuda cuda_arch=86 %gcc@13 ^cuda@12.4
```

A instalação é demorada (quase 2 horas).


### Verificar a instalação do Pytorch

Vamos verificar se Pytorch está funcionando com CUDA. 

Vamos criar o seguinte *script* Python (`test-cuda.py`):

```{python}
#! /usr/bin/env python

# test-cuda.py

import os
import torch

x = torch.rand(5, 3)
print(x)
print("torch.__version__            =", torch.__version__)
print("torch.version.cuda           =", torch.version.cuda)
print("torch.backends.cuda.is_built =", torch.backends.cuda.is_built())
print("torch.cuda.is_available      =", torch.cuda.is_available())
print("torch.cuda.device_count      =", torch.cuda.device_count())

if torch.cuda.is_available():
    print("device 0 name               =", torch.cuda.get_device_name(0))
```

Tornamos o arquivo executável:

```{bash}
chmod u+x test-cuda.py
```

Vamos para um *shell* em um nó de GPU:

```{bash}
srun --partition=gpu --gres=gpu:1 --time=00:05:00 --pty bash
```

No nó de GPU, carregamos os pacotes necessários e rodamos o *script*:

```{bash}
spack load python@3.11
spack load py-torch
./test-cuda.py
```

A saída é

```
tensor([[0.8326, 0.2251, 0.9847],
        [0.4171, 0.1580, 0.4783],
        [0.6500, 0.7902, 0.9062],
        [0.9074, 0.7503, 0.4135],
        [0.7938, 0.6857, 0.9237]])
torch.__version__            = 2.5.1
torch.version.cuda           = 12.4
torch.backends.cuda.is_built = True
torch.cuda.is_available      = True
torch.cuda.device_count      = 1
device 0 name               = NVIDIA A2
```

[O Pytorch está instalado, com acesso à GPU.]{.hl}


### Instalar o Uni-core

Temos 3 opções:

1. Instalar um *wheel* pré-compilado,
1. Compilar o fonte,
1. Instalar uma imagem do Docker.


#### Instalar um *wheel* pré-compilado (falhou)

[No repositório do Uni-core](https://github.com/dptech-corp/Uni-Core), estão disponíveis os seguintes *wheels*:

- unicore-0.0.1+cu117torch2.0.0-cp310-cp310-linux\_x86\_64.whl,
- unicore-0.0.1+cu117torch2.0.0-cp38-cp38-linux\_x86\_64.whl,
- unicore-0.0.1+cu117torch2.0.0-cp39-cp39-linux\_x86\_64.whl,
- unicore-0.0.1+cu118torch2.0.0-cp310-cp310-linux\_x86\_64.whl,
- unicore-0.0.1+cu118torch2.0.0-cp38-cp38-linux\_x86\_64.whl,
- unicore-0.0.1+cu118torch2.0.0-cp39-cp39-linux\_x86\_64.whl.

O número depois de `cu` é a versão do CUDA, e o número depois de `cp` é a versão do Python.

::: {.callout-caution title="Versões diferentes"}

Estamos com CUDA 12.4, Pytorch 2.5.1 e Python 3.11.9.

Nenhum destes *wheels* serve para o nosso ambiente.

Vamos compilar o Uni-core a partir do fonte.

:::


#### Compilar a partir do fonte

Do [README do repositório do Uni-core](https://github.com/dptech-corp/Uni-Core/blob/main/README.md):

> You can use `python setup.py install` or `pip install .` to build Uni-Core from source. The CUDA version in the build environment should be the same as the one in PyTorch.

Vamos supor que já temos os seguintes pacotes no sistema (podemos conferir com `spack find`):

- `python@3.11.9`
- `py-torch@2.5.1`
- `py-typing-extensions@4.12.2`
- `py-sympy@1.13.0`

Vamos supor, também, que já clonamos o repositório do Uni-core para `~/BioSensIA/Uni-Core`.


##### Criar um ambiente virtual (Spack)

```{bash}
cd ~/BioSensIA/Uni-Core
spack env create --dir .
spack env activate .
```


##### Editar o arquivo `spack.yaml`

O conteúdo do arquivo deve ser:

```{yaml}
spack:
  specs:
  - python@3.11.9
  - py-pip
  - py-torch@2.5.1
  - py-typing-extensions@4.12.2
  - py-sympy@1.13.0
  view: ./view
  concretizer:
    unify: true
```


##### Concretizar e instalar

```{bash}
spack concretize -f
spack install
```


##### Criar um ambiente virtual (venv)

```{bash}
./view/bin/python -m venv .venv
source .venv/bin/activate

python -m ensurepip --upgrade
python -m pip install --upgrade pip setuptools wheel

python - <<'PY'
import pathlib, site
venv_site = pathlib.Path(site.getsitepackages()[0])
pth = venv_site / "spack_view_torch.pth"
pth.write_text(str(pathlib.Path("view/lib/python3.11/site-packages").resolve()) + "\n")
print(pth)
PY
```


##### Verificar se o Pytorch está visível

```{bash}
python -c "import torch, sys; print(sys.executable); print(torch.__version__); print(torch.__file__)"
```


##### Instalar o Uni-core

```{bash}
python setup.py install
```

[Depois disto, o *script* `unicore-train` estará instalado em `~/BioSensIA/Uni-Core/.venv/bin`.]{.hl}


### Testar instalação do Uni-core

???

wikitext não estava disponível no url dado. Baixei de https://www.kaggle.com/datasets/bestwater/wikitext-2-v1?resource=download

???

